export const FETCH_REPO_REQUEST = 'FETCH_REPO_REQUEST';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS';
export const FETCH_REPO_ERROR = 'FETCH_REPO_ERROR';

export const FETCH_USER_REPO_REQUEST = 'FETCH_USER_REPO_REQUEST';
export const FETCH_USER_REPO_SUCCESS = 'FETCH_USER_REPO_SUCCESS';
export const FETCH_USER_REPO_ERROR = 'FETCH_USER_REPO_ERROR';
